# 使用 Node.js 作为构建阶段
FROM node:16 as build-stage
WORKDIR /app

# 设置 npm 镜像源
RUN npm config set registry https://registry.npmmirror.com

# 复制 package.json 和 package-lock.json
COPY package*.json ./

# 安装依赖
RUN npm install

# 复制项目文件
COPY . .

# 添加执行权限
RUN chmod +x ./node_modules/.bin/*

# 构建项目
RUN npm run build:dev

# 使用 Nginx 作为生产阶段
FROM nginx:stable-alpine as production-stage

# 清空默认的 Nginx 配置
RUN rm -rf /etc/nginx/conf.d/*

# 复制 Nginx 配置文件
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# 复制构建后的文件到 Nginx 目录
COPY --from=build-stage /app/dist /usr/share/nginx/html

# 暴露端口
EXPOSE 3070

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]